---

- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian","Ubuntu"]

    - name: Install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Add PHP support for Apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
